<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Dal\Dal.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Box.V2.Core" Version="5.8.0" />
    <PackageReference Include="Dropbox.Api" Version="7.0.0" />
    <PackageReference Include="FluentFTP" Version="54.2.0" />
    <PackageReference Include="HashLib" Version="2.0.1" />
    <PackageReference Include="Inflatable.Lastfm" Version="1.2.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NLayer" Version="1.16.0" />
    <PackageReference Include="NLayer.NAudioSupport" Version="1.4.0" />
    <PackageReference Include="StreamRipper" Version="2.1.10" />
  </ItemGroup>
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
